server:
  port: 8080
  servlet:
    context-path: /scaffold
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scaffold?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 112233

mybatis-plus:
  # 扫描枚举包，让mybatis-plus映射
  type-enums-package: cn.pangchun.scaffold.blog.enums